### ISSUE TITLE
Medium Size Widget Support

### ISSUE THREAD

**Issue by ghost** [italoboy/Full-Weatherline-Widget#2]
Hello, I would love to see support for a medium size widget where the user can choose what elements to keep.

**Comment by italoboy** [comment]
Well medium widget (Weatherline widgets) has been released before, even the small size.
This is not possible to fit.

**Comment by ghost** [comment]
Even if most elements are left out?

**Comment by italoboy** [comment]
> 
> 
> Even if most elements are left out?

Added in Update 3.

**Comment by ghost** [comment]
Ok, thanks.
